fix: use proper custom scope when being passed via params
storyblok/app-extension-auth pull request #2
Opened 2023-05-03 23:03 UTC by marckraw

2023-05-04 08:37 UTC, johannes-lindgren requested changes

2023-05-04 08:37 UTC, johannes-lindgren commented on src/storyblok-auth-api/grant/grant-handler.ts
> +          scope: scope ? scope : ['read_content'],
```suggestion
          scope,
```

The scope is a required parameter, so no need to use a fallback value

2023-05-12 15:59 UTC, closed without merging

2023-05-15 07:33 UTC, marckraw commented
@johannes-lindgren should I have access to this endpoint though ? (its not on your list), can i find a list of available endpoints somewhere ? 

```
spaces/${spaceId}/presets/${p.preset.id}
```

2023-05-15 07:39 UTC, marckraw commented
ah ok i just saw, multiple presets doesnt work..

2023-07-11 10:46 UTC, chrsbrmr commented
are there any updates on this? since my accessToken isn´t authorized for anything.

2023-07-11 11:21 UTC, marckraw commented
@johannes-lindgren yes, is there a way to see what are the status of the exposing API endpoints ?